// Renders the iOS home-screen launch (splash) screens: the app icon centred
// with the Kiln wordmark below it, light and dark, one PNG per device size
// Apple documents. pwa-asset-generator screenshots the HTML at every device
// resolution and injects the <link rel="apple-touch-startup-image"> tags
// into index.html. Uses the pre-installed Chromium via CHROME_PATH.
import { generateImages } from "pwa-asset-generator"
import {
  chmodSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import { join, resolve } from "node:path"

const tmp = mkdtempSync(join(tmpdir(), "kiln-splash-"))

// chrome-launcher exposes no hook for --no-sandbox, which Chromium needs
// when running as root (the agent/CI container) — hand it a wrapper script.
// On a normal dev machine leave CHROME_PATH alone so it finds system Chrome.
const chromium = process.env.CHROMIUM_PATH || "/opt/pw-browsers/chromium"
if (!process.env.CHROME_PATH && existsSync(chromium)) {
  const wrapper = join(tmp, "chromium-no-sandbox.sh")
  writeFileSync(wrapper, `#!/bin/sh\nexec "${chromium}" --no-sandbox "$@"\n`)
  chmodSync(wrapper, 0o755)
  process.env.CHROME_PATH = wrapper
}

const icon = readFileSync(resolve("public/icons/icon.svg"), "utf8")

// vmin sizing keeps the mark proportional across every device resolution.
// Font stack mirrors the app's --font-serif (Liberation Serif is the
// Times-metric fallback available in the container).
const page = (bg, fg) => `<!doctype html>
<html><head><meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  html, body { margin: 0; height: 100%; }
  body { background: ${bg}; display: flex; align-items: center; justify-content: center; }
  .mark { display: flex; flex-direction: column; align-items: center; gap: 5.5vmin; }
  .mark svg { width: 26vmin; height: 26vmin; }
  .mark span {
    color: ${fg};
    font: 600 7vmin Georgia, "Times New Roman", "Liberation Serif", serif;
    letter-spacing: 0.02em;
  }
</style></head>
<body><div class="mark">${icon}<span>Kiln</span></div></body></html>`

const light = join(tmp, "light.html")
const dark = join(tmp, "dark.html")
writeFileSync(light, page("#faf9f5", "#1f1e1b"))
writeFileSync(dark, page("#262624", "#f0efea"))

const common = {
  splashOnly: true,
  portraitOnly: true, // manifest locks orientation to portrait
  type: "png",
  pathOverride: "/splash",
  favicon: false,
  xhtml: false,
  log: false,
  // Use the device list bundled with the package instead of scraping
  // Apple's docs at run time, so regeneration is deterministic/offline.
  scrape: false,
}

// The package's own --index injection reformats the whole file (and pushes
// <meta charset> out of the first 1024 bytes), so splice the tags into the
// marker block in index.html ourselves instead.
const lightRun = await generateImages(light, "public/splash", common)
const darkRun = await generateImages(dark, "public/splash", {
  ...common,
  darkMode: true,
})
rmSync(tmp, { recursive: true, force: true })

const indent = "    "
const reindent = (tags) =>
  tags
    .trim()
    .split("\n")
    .map((l) => indent + l.trim())
    .join("\n")
const block = [
  `${indent}<!-- splash:generated by \`npm run splash\` — do not edit by hand -->`,
  reindent(lightRun.htmlMeta.appleLaunchImage),
  reindent(darkRun.htmlMeta.appleLaunchImageDarkMode),
  `${indent}<!-- /splash:generated -->`,
].join("\n")

const indexPath = resolve("index.html")
let html = readFileSync(indexPath, "utf8")
const marker = /[ \t]*<!-- splash:generated[\s\S]*?<!-- \/splash:generated -->/
html = marker.test(html)
  ? html.replace(marker, block)
  : html.replace(/^[ \t]*<\/head>/m, `${block}\n  </head>`)
writeFileSync(indexPath, html)
console.log(
  `wrote ${lightRun.savedImages.length + darkRun.savedImages.length} images to public/splash + startup-image tags in index.html`,
)
